name = "TokenIterators"
uuid = "c6f4ec34-39d0-4d8f-98bd-3b6eb0e88111"
authors = ["Josh Day <emailjoshday@gmail.com> and contributors"]
version = "0.0.1"

[deps]
StringViews = "354b36f9-a18e-4713-926e-db85100087ba"
StyledStrings = "f489334b-da3d-4c2e-b8f0-e476e12c162b"

[compat]
Downloads = "1.6.0"
StringViews = "1.3.4"
StyledStrings = "1.11.0"
julia = "1.10.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"

[targets]
test = ["Test", "Downloads"]
