name = "StreamParse"
uuid = "c6f4ec34-39d0-4d8f-98bd-3b6eb0e88111"
authors = ["Josh Day <emailjoshday@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
